-- MySQL Script generated by MySQL Workbench
-- Mon Aug  5 21:41:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rhino-pap
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rhino-pap
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rhino-pap` DEFAULT CHARACTER SET utf8 ;
USE `rhino-pap` ;

-- -----------------------------------------------------
-- Table `rhino-pap`.`Organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhino-pap`.`Organization` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhino-pap`.`Team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhino-pap`.`Team` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `Organization_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Organization_id`),
  INDEX `fk_Team_Organization1_idx` (`Organization_id` ASC),
  CONSTRAINT `fk_Team_Organization1`
    FOREIGN KEY (`Organization_id`)
    REFERENCES `rhino-pap`.`Organization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhino-pap`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhino-pap`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `ldap_ref` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhino-pap`.`Team_has_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhino-pap`.`Team_has_User` (
  `team_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`team_id`, `user_id`),
  INDEX `fk_Team_has_User_User1_idx` (`user_id` ASC),
  INDEX `fk_Team_has_User_Team_idx` (`team_id` ASC),
  CONSTRAINT `fk_Team_has_User_Team`
    FOREIGN KEY (`team_id`)
    REFERENCES `rhino-pap`.`Team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Team_has_User_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `rhino-pap`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhino-pap`.`Platform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhino-pap`.`Platform` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhino-pap`.`Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhino-pap`.`Service` (
  `id` INT NOT NULL,
  `Platform_id` INT NOT NULL,
  `service_name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`, `Platform_id`),
  INDEX `fk_Service_Platform1_idx` (`Platform_id` ASC),
  CONSTRAINT `fk_Service_Platform1`
    FOREIGN KEY (`Platform_id`)
    REFERENCES `rhino-pap`.`Platform` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhino-pap`.`Project Owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhino-pap`.`Project Owner` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhino-pap`.`Setup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhino-pap`.`Setup` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number_of_nodes` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhino-pap`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhino-pap`.`Project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `Project Owner_id` INT NOT NULL,
  `Platform_id` INT NOT NULL,
  `Setup_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Project Owner_id`, `Platform_id`, `Setup_id`),
  INDEX `fk_Project_Project Owner1_idx` (`Project Owner_id` ASC),
  INDEX `fk_Project_Platform1_idx` (`Platform_id` ASC),
  INDEX `fk_Project_Setup1_idx` (`Setup_id` ASC),
  CONSTRAINT `fk_Project_Project Owner1`
    FOREIGN KEY (`Project Owner_id`)
    REFERENCES `rhino-pap`.`Project Owner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Project_Platform1`
    FOREIGN KEY (`Platform_id`)
    REFERENCES `rhino-pap`.`Platform` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Project_Setup1`
    FOREIGN KEY (`Setup_id`)
    REFERENCES `rhino-pap`.`Setup` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhino-pap`.`Job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhino-pap`.`Job` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Project_id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `simulation_id` VARCHAR(45) NULL,
  `influx_ref` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `Project_id`),
  INDEX `fk_Job_Project1_idx` (`Project_id` ASC),
  CONSTRAINT `fk_Job_Project1`
    FOREIGN KEY (`Project_id`)
    REFERENCES `rhino-pap`.`Project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhino-pap`.`Project_has_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhino-pap`.`Project_has_User` (
  `Project_id` INT NOT NULL,
  `Project_Project Owner_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`Project_id`, `Project_Project Owner_id`, `User_id`),
  INDEX `fk_Project_has_User_User1_idx` (`User_id` ASC),
  INDEX `fk_Project_has_User_Project1_idx` (`Project_id` ASC, `Project_Project Owner_id` ASC),
  CONSTRAINT `fk_Project_has_User_Project1`
    FOREIGN KEY (`Project_id` , `Project_Project Owner_id`)
    REFERENCES `rhino-pap`.`Project` (`id` , `Project Owner_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Project_has_User_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `rhino-pap`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rhino-pap`.`Team_has_Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rhino-pap`.`Team_has_Project` (
  `Team_id` INT NOT NULL,
  `Project_id` INT NOT NULL,
  `Project_Project Owner_id` INT NOT NULL,
  PRIMARY KEY (`Team_id`, `Project_id`, `Project_Project Owner_id`),
  INDEX `fk_Team_has_Project_Project1_idx` (`Project_id` ASC, `Project_Project Owner_id` ASC),
  INDEX `fk_Team_has_Project_Team1_idx` (`Team_id` ASC),
  CONSTRAINT `fk_Team_has_Project_Team1`
    FOREIGN KEY (`Team_id`)
    REFERENCES `rhino-pap`.`Team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Team_has_Project_Project1`
    FOREIGN KEY (`Project_id` , `Project_Project Owner_id`)
    REFERENCES `rhino-pap`.`Project` (`id` , `Project Owner_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
